'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { SignalText as SignalTextElement, defineCustomElement as defineSignalText } from "@signal-web-ui/core/dist/custom-elements/signal-text.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalTextEvents = NonNullable<unknown>;

export const SignalText: StencilReactComponent<SignalTextElement, SignalTextEvents> = /*@__PURE__*/ createComponent<SignalTextElement, SignalTextEvents>({
    tagName: 'signal-text',
    elementClass: SignalTextElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SignalTextEvents,
    defineCustomElement: defineSignalText
});
