'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalFeatureTableCustomEvent } from "@signal-web-ui/core";
import { SignalFeatureTable as SignalFeatureTableElement, defineCustomElement as defineSignalFeatureTable } from "@signal-web-ui/core/dist/custom-elements/signal-feature-table.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalFeatureTableEvents = {
    onRowClick: EventName<SignalFeatureTableCustomEvent<{ row: Record<string, unknown> }>>,
    onSelectionChanged: EventName<SignalFeatureTableCustomEvent<{ keys: string[] }>>,
    onSortChange: EventName<SignalFeatureTableCustomEvent<{ sort?: { key: string; direction: "asc" | "desc" } }>>,
    onFilterChange: EventName<SignalFeatureTableCustomEvent<{ filters: Record<string, string> }>>,
    onSearchChange: EventName<SignalFeatureTableCustomEvent<{ query: string }>>,
    onPageChange: EventName<SignalFeatureTableCustomEvent<{ pageIndex: number; pageSize: number }>>
};

export const SignalFeatureTable: StencilReactComponent<SignalFeatureTableElement, SignalFeatureTableEvents> = /*@__PURE__*/ createComponent<SignalFeatureTableElement, SignalFeatureTableEvents>({
    tagName: 'signal-feature-table',
    elementClass: SignalFeatureTableElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onRowClick: 'rowClick',
        onSelectionChanged: 'selectionChanged',
        onSortChange: 'sortChange',
        onFilterChange: 'filterChange',
        onSearchChange: 'searchChange',
        onPageChange: 'pageChange'
    } as SignalFeatureTableEvents,
    defineCustomElement: defineSignalFeatureTable
});
