'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { SignalTooltip as SignalTooltipElement, defineCustomElement as defineSignalTooltip } from "@signal-web-ui/core/dist/custom-elements/signal-tooltip.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalTooltipEvents = NonNullable<unknown>;

export const SignalTooltip: StencilReactComponent<SignalTooltipElement, SignalTooltipEvents> = /*@__PURE__*/ createComponent<SignalTooltipElement, SignalTooltipEvents>({
    tagName: 'signal-tooltip',
    elementClass: SignalTooltipElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SignalTooltipEvents,
    defineCustomElement: defineSignalTooltip
});
