'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalFileUploadCustomEvent } from "@signal-web-ui/core";
import { SignalFileUpload as SignalFileUploadElement, defineCustomElement as defineSignalFileUpload } from "@signal-web-ui/core/dist/custom-elements/signal-file-upload.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalFileUploadEvents = {
  onSelect: EventName<SignalFileUploadCustomEvent<{ files: File[] }>>;
  onUpload: EventName<SignalFileUploadCustomEvent<{ files: File[] }>>;
  onRemove: EventName<SignalFileUploadCustomEvent<{ file: File }>>;
};

export const SignalFileUpload: StencilReactComponent<SignalFileUploadElement, SignalFileUploadEvents> = /*@__PURE__*/ createComponent<SignalFileUploadElement, SignalFileUploadEvents>({
  tagName: 'signal-file-upload',
  elementClass: SignalFileUploadElement,
  // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
  react: React,
  events: {
    onSelect: 'select',
    onUpload: 'upload',
    onRemove: 'remove'
  } as SignalFileUploadEvents,
  defineCustomElement: defineSignalFileUpload
});
