'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalListItemCustomEvent } from "@signal-web-ui/core";
import { SignalListItem as SignalListItemElement, defineCustomElement as defineSignalListItem } from "@signal-web-ui/core/dist/custom-elements/signal-list-item.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalListItemEvents = { onItemClick: EventName<SignalListItemCustomEvent<void>> };

export const SignalListItem: StencilReactComponent<SignalListItemElement, SignalListItemEvents> = /*@__PURE__*/ createComponent<SignalListItemElement, SignalListItemEvents>({
    tagName: 'signal-list-item',
    elementClass: SignalListItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onItemClick: 'itemClick' } as SignalListItemEvents,
    defineCustomElement: defineSignalListItem
});
