'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { SignalHeading as SignalHeadingElement, defineCustomElement as defineSignalHeading } from "@signal-web-ui/core/dist/custom-elements/signal-heading.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalHeadingEvents = NonNullable<unknown>;

export const SignalHeading: StencilReactComponent<SignalHeadingElement, SignalHeadingEvents> = /*@__PURE__*/ createComponent<SignalHeadingElement, SignalHeadingEvents>({
    tagName: 'signal-heading',
    elementClass: SignalHeadingElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SignalHeadingEvents,
    defineCustomElement: defineSignalHeading
});
