'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { SignalSkeleton as SignalSkeletonElement, defineCustomElement as defineSignalSkeleton } from "@signal-web-ui/core/dist/custom-elements/signal-skeleton.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalSkeletonEvents = NonNullable<unknown>;

export const SignalSkeleton: StencilReactComponent<SignalSkeletonElement, SignalSkeletonEvents> = /*@__PURE__*/ createComponent<SignalSkeletonElement, SignalSkeletonEvents>({
    tagName: 'signal-skeleton',
    elementClass: SignalSkeletonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as SignalSkeletonEvents,
    defineCustomElement: defineSignalSkeleton
});
