'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SignalDataTableCustomEvent } from "@signal-web-ui/core";
import { SignalDataTable as SignalDataTableElement, defineCustomElement as defineSignalDataTable } from "@signal-web-ui/core/dist/custom-elements/signal-data-table.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type SignalDataTableEvents = { onRowClick: EventName<SignalDataTableCustomEvent<{ row: Record<string, unknown> }>> };

export const SignalDataTable: StencilReactComponent<SignalDataTableElement, SignalDataTableEvents> = /*@__PURE__*/ createComponent<SignalDataTableElement, SignalDataTableEvents>({
    tagName: 'signal-data-table',
    elementClass: SignalDataTableElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onRowClick: 'rowClick' } as SignalDataTableEvents,
    defineCustomElement: defineSignalDataTable
});
